export const TH6_CAPS: Record<string, number> = {
  town_hall: 1,
  clan_castle: 1,
  cannon: 4,
  archer_tower: 3,
  mortar: 2,
  air_defense: 2,
  air_sweeper: 1,
  wizard_tower: 2,
  gold_mine: 6,
  elixir_collector: 6,
  gold_storage: 2,
  elixir_storage: 2,
  army_camp: 4,
  barracks: 3,
  laboratory: 1,
  spell_factory: 1,
  builders_hut: 5,
  wall: 75,
  bomb: 4,
  giant_bomb: 1,
  spring_trap: 4,
  air_bomb: 2,
};
