export const TH6_CAPS: Record<string, number> = {
  town_hall: 1,
  clan_castle: 1,
  cannon: 2,
  archer_tower: 2,
  mortar: 1,
  air_defense: 1,
  wizard_tower: 1,
  gold_mine: 4,
  elixir_collector: 4,
  gold_storage: 2,
  elixir_storage: 2,
  army_camp: 4,
  barracks: 4,
  laboratory: 1,
  spell_factory: 1,
  builders_hut: 5,
  wall: 75,
};
