"""Generate TypeScript type definitions from the Pydantic v2 schemas.

Sandbox-web never declares its own duplicate of any sim schema — every TS type
comes from this generator. The output file is committed so the web project can
build without invoking Python.

Usage:
    uv run python -m sandbox_core.tools.generate_types          # rewrite the file
    uv run python -m sandbox_core.tools.generate_types --check  # drift check

See `app/docs/sandbox/prd.md` §3.2 (FR-W9) and §6 (data contracts).
"""

from __future__ import annotations

import argparse
import inspect
import sys
import types
from collections.abc import Iterable
from enum import StrEnum
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin

from pydantic import BaseModel

from sandbox_core import schemas

DEFAULT_OUT = Path("app/sandbox_web/src/generated_types.ts")

HEADER = """\
// AUTOGENERATED — DO NOT EDIT.
//
// Generated from app/sandbox_core/schemas.py by:
//   uv run python -m sandbox_core.tools.generate_types
//
// After editing the Pydantic schemas, regenerate this file and commit the
// result. CI and pre-commit fail if this file drifts from the schemas.
"""


def _is_public_model(obj: object) -> bool:
    return (
        inspect.isclass(obj)
        and issubclass(obj, BaseModel)
        and obj is not BaseModel
        and not obj.__name__.startswith("_")
        and obj.__module__ == schemas.__name__
    )


def _is_public_strenum(obj: object) -> bool:
    return (
        inspect.isclass(obj)
        and issubclass(obj, StrEnum)
        and obj is not StrEnum
        and not obj.__name__.startswith("_")
        and obj.__module__ == schemas.__name__
    )


def _ts_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, int | float):
        return str(value)
    raise TypeError(f"unsupported literal value {value!r}")


def ts_type(annotation: Any) -> str:
    if annotation is type(None):
        return "null"

    origin = get_origin(annotation)

    if origin is Literal:
        return " | ".join(_ts_literal(a) for a in get_args(annotation))

    if origin in (Union, types.UnionType):
        args = get_args(annotation)
        non_none = [a for a in args if a is not type(None)]
        parts = [ts_type(a) for a in non_none]
        if type(None) in args:
            parts.append("null")
        return " | ".join(parts)

    if origin is list:
        (item,) = get_args(annotation)
        return f"{ts_type(item)}[]"

    if origin is tuple:
        args = get_args(annotation)
        if len(args) == 2 and args[1] is Ellipsis:
            return f"{ts_type(args[0])}[]"
        items = ", ".join(ts_type(a) for a in args)
        return f"[{items}]"

    if origin is dict:
        kt, vt = get_args(annotation)
        if kt is not str:
            raise TypeError(f"only string-keyed dicts supported, got key type {kt!r}")
        return f"{{ [key: string]: {ts_type(vt)} }}"

    if annotation is str:
        return "string"
    if annotation is bool:
        return "boolean"
    if annotation in (int, float):
        return "number"
    if annotation is Any:
        return "unknown"

    if inspect.isclass(annotation):
        if issubclass(annotation, BaseModel):
            return annotation.__name__
        if issubclass(annotation, StrEnum):
            return annotation.__name__

    raise TypeError(f"unsupported type annotation: {annotation!r}")


def emit_enum(cls: type[StrEnum]) -> str:
    members = sorted((m.value for m in cls), key=str)
    body = "\n  | ".join(f'"{m}"' for m in members)
    return f"export type {cls.__name__} =\n  | {body};\n"


def emit_model(cls: type[BaseModel]) -> str:
    lines = [f"export interface {cls.__name__} {{"]
    for name, field in cls.model_fields.items():
        lines.append(f"  {name}: {ts_type(field.annotation)};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _public_enums() -> list[type[StrEnum]]:
    return sorted(
        (obj for obj in vars(schemas).values() if _is_public_strenum(obj)),
        key=lambda c: c.__name__,
    )


def _public_models() -> list[type[BaseModel]]:
    return sorted(
        (obj for obj in vars(schemas).values() if _is_public_model(obj)),
        key=lambda c: c.__name__,
    )


def _join(parts: Iterable[str]) -> str:
    return "\n".join(parts)


def generate() -> str:
    """Return the full text of `generated_types.ts`."""
    sections: list[str] = [HEADER, f"export const SCHEMA_VERSION = {schemas.SCHEMA_VERSION};\n"]
    sections.extend(emit_enum(cls) for cls in _public_enums())
    sections.extend(emit_model(cls) for cls in _public_models())
    return _join(sections)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="generate-types",
        description="Generate TypeScript types from Pydantic schemas.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"output file (default: {DEFAULT_OUT})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed file differs from regenerated output",
    )
    args = parser.parse_args(argv)

    generated = generate()

    if args.check:
        if not args.out.exists():
            print(
                f"error: {args.out} does not exist — run "
                "`uv run python -m sandbox_core.tools.generate_types` and commit the result.",
                file=sys.stderr,
            )
            return 1
        committed = args.out.read_text(encoding="utf-8")
        if committed != generated:
            print(
                f"error: {args.out} is out of date with app/sandbox_core/schemas.py.\n"
                "Run `uv run python -m sandbox_core.tools.generate_types` "
                "and commit the result.",
                file=sys.stderr,
            )
            return 1
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(generated, encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
