// AUTOGENERATED — DO NOT EDIT.
//
// Generated from app/sandbox_core/schemas.py by:
//   uv run python -m sandbox_core.tools.generate_types
//
// After editing the Pydantic schemas, regenerate this file and commit the
// result. CI and pre-commit fail if this file drifts from the schemas.

export const SCHEMA_VERSION = 1;

export type AttackKind =
  | "melee"
  | "ranged"
  | "spell_bolt"
  | "suicide";

export type BuildingCategory =
  | "army"
  | "builder_hut"
  | "clan_castle"
  | "defense"
  | "resource_collector"
  | "resource_storage"
  | "town_hall"
  | "wall";

export type EventType =
  | "attack_end"
  | "attack_start"
  | "bolt_struck"
  | "damage"
  | "deploy"
  | "destroyed"
  | "end_attack"
  | "projectile_fired"
  | "sim_terminated"
  | "spell_cast"
  | "target_acquired"
  | "target_lost";

export type TargetFilter =
  | "air"
  | "all_except_walls"
  | "both"
  | "ground";

export type TargetPreference =
  | "defenses"
  | "none"
  | "resources"
  | "walls";

export type TroopCategory =
  | "air"
  | "ground";

export interface BaseLayout {
  schema_version: 1;
  metadata: BaseLayoutMetadata;
  th_level: number;
  placements: BuildingPlacement[];
  cc_contents: string[];
}

export interface BaseLayoutMetadata {
  name: string;
  th_level: number;
  tags: string[];
  notes: string | null;
  author: string;
  created_at: string;
}

export interface BuildingLevelStats {
  level: number;
  hp: number;
  damage_per_shot: number;
  range_tiles: number;
  attack_cooldown_ticks: number;
  unlocked_at_th: number;
}

export interface BuildingPlacement {
  building_type: string;
  origin: [number, number];
  level: number | null;
}

export interface BuildingState {
  id: number;
  building_type: string;
  origin: [number, number];
  level: number;
  hp: number;
  max_hp: number;
  destroyed: boolean;
}

export interface BuildingType {
  name: string;
  category: BuildingCategory;
  footprint: [number, number];
  hitbox_inset: number | null;
  target_filter: TargetFilter;
  splash_radius_tiles: number;
  splash_damages_walls: boolean;
  min_range_tiles: number;
  projectile_speed_tiles_per_sec: number | null;
  projectile_homing: boolean;
  is_wall: boolean;
  damages_walls_on_suicide: boolean;
  levels: BuildingLevelStats[];
}

export interface DeploymentAction {
  tick: number;
  kind: "deploy_troop" | "cast_spell";
  entity_type: string;
  position: [number, number];
  level: number | null;
}

export interface DeploymentPlan {
  schema_version: 1;
  metadata: DeploymentPlanMetadata;
  actions: DeploymentAction[];
}

export interface DeploymentPlanMetadata {
  name: string;
  notes: string | null;
  author: string;
  created_at: string;
}

export interface Event {
  type: EventType;
  tick: number;
  payload: { [key: string]: unknown };
}

export interface Projectile {
  id: number;
  attacker_id: number;
  target_id: number | null;
  attack_kind: AttackKind;
  attacker_position: [number, number];
  current_position: [number, number];
  impact_position: [number, number];
  damage: number;
  splash_radius_tiles: number;
  splash_damages_walls: boolean;
  ticks_to_impact: number;
}

export interface Replay {
  schema_version: 1;
  metadata: ReplayMetadata;
  initial_state: WorldState;
  frames: TickFrame[];
}

export interface ReplayMetadata {
  sim_version: string;
  base_name: string;
  plan_name: string;
  run_id: string;
  episode_id: string;
  total_ticks: number;
  final_score: Score;
  started_at: string;
  git_sha: string;
  config_hash: string;
}

export interface Score {
  stars: number;
  destruction_pct: number;
  ticks_elapsed: number;
  town_hall_destroyed: boolean;
}

export interface SpellCast {
  id: number;
  spell_type: string;
  level: number;
  center: [number, number];
  cast_tick: number;
  bolts_remaining: number;
  next_bolt_tick: number;
}

export interface SpellLevelStats {
  level: number;
  damage_per_hit: number;
  unlocked_at_th: number;
}

export interface SpellType {
  name: string;
  radius_tiles: number;
  hit_interval_ticks: number;
  num_hits: number;
  damages_walls: boolean;
  target_filter: TargetFilter;
  housing_space: number;
  levels: SpellLevelStats[];
}

export interface TickFrame {
  tick: number;
  state: WorldState;
  events: Event[];
}

export interface TroopLevelStats {
  level: number;
  hp: number;
  base_damage: number;
  range_tiles: number;
  attack_cooldown_ticks: number;
  unlocked_at_th: number;
}

export interface TroopState {
  id: number;
  troop_type: string;
  level: number;
  position: [number, number];
  hp: number;
  max_hp: number;
  destroyed: boolean;
}

export interface TroopType {
  name: string;
  category: TroopCategory;
  footprint: [number, number];
  hitbox_radius_tiles: number;
  housing_space: number;
  speed_tiles_per_sec: number;
  target_filter: TargetFilter;
  target_preference: TargetPreference;
  splash_radius_tiles: number;
  splash_damages_walls: boolean;
  projectile_speed_tiles_per_sec: number | null;
  projectile_homing: boolean;
  damages_walls_on_suicide: boolean;
  damage_multipliers: { [key: string]: number };
  damage_multiplier_default: number;
  levels: TroopLevelStats[];
}

export interface WorldState {
  tick: number;
  buildings: BuildingState[];
  troops: TroopState[];
  projectiles: Projectile[];
  spells: SpellCast[];
  score: Score;
}
